### ISSUE TITLE
getCode() with not supported language name

### ISSUE THREAD

**Issue by fnyrdrjh** [meikidd/iso-639-1#7]
Unlike `getName()` that returns an empty string when called with a non-ISO language code, `getCode()` throws an exception when called with a non-canonical, misspelled or inexistent language name:
`iso.getCode('Tibetan'); // supposed to be Tibetan Standard...`

```
~/project/node_modules/babel-runtime/helpers/slicedToArray.js:48
      throw new TypeError("Invalid attempt to destructure non-iterable instance");
      ^

TypeError: Invalid attempt to destructure non-iterable instance
    at ~/project/node_modules/babel-runtime/helpers/slicedToArray.js:48:13
    at Function.ISO6391.getCode (/home/ubuntu/projects/learn_bpe/node_modules/iso-639-1/build/index.js:85:59)
    at Object.<anonymous> (/home/ubuntu/projects/learn_bpe/cli.js:61:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

_(node v6.8.1 under ubuntu 14.04)_

**Comment by meikidd** [comment]
`getName() / getNativeName() / getCode()` returns empty string when called with a non-ISO language. 

fixed and v1.2.5 published for this issue. thx.
